---
title: "Sta 325 Final Project"
author: "Calleigh Smith, Hannah Bogomilsky, Hugh Esterson, Maria Henriquez, Mariana Izon"
date: "11/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-packages, message=FALSE}
library(readr)
library(dplyr)
library(tidyverse)
```

```{r load-clean-data, message=FALSE}
flights <- read_csv("data/flights.csv")

unique(flights$OP_CARRIER)
unique(flights$DEST)
class(flights$CARRIER_DELAY)

flights <- flights %>% 
  mutate(CARRIER_DELAY = case_when(CARRIER_DELAY > 0 ~ 1),
         WEATHER_DELAY = case_when(WEATHER_DELAY > 0 ~ 1),
         NAS_DELAY = case_when(NAS_DELAY > 0 ~ 1),
         SECURITY_DELAY = case_when(SECURITY_DELAY > 0 ~ 1),
         LATE_AIRCRAFT_DELAY = case_when(LATE_AIRCRAFT_DELAY > 0 ~ 1))

```

```{r}
flights
```

## Taxi Histograms

```{r}
ggplot(data = flights, aes(x = TAXI_IN)) +
  geom_histogram(binwidth = 5, fill = "#E81828", color = "#002D72") +
  labs(x = "Time to Taxi In",
       title = "Histogram of TAXI_IN")

ggplot(data = flights, aes(x = TAXI_OUT)) +
  geom_histogram(binwidth = 5, fill = "#E81828", color = "#002D72") +
  labs(x = "Time to Taxi Out",
       title = "Histogram of TAXI_OUT")
```

## Delay Histograms

```{r}
ggplot(data = flights, aes(x = ARR_DELAY)) +
  geom_histogram(binwidth = 20, fill = "#E81828", color = "#002D72") +
  xlim(-100, 150) +
  labs(x = "Arrival Delay",
       title = "Histogram of ARR_DELAY")

ggplot(data = flights, aes(x = DEP_DELAY)) +
  geom_histogram(binwidth = 4, fill = "#E81828", color = "#002D72") +
  xlim(-25, 50) +
  labs(x = "Departure Delay",
       title = "Histogram of DEP_DELAY")
```

